#!/bin/bash

#SBATCH --mail-type=none
#SBATCH --job-name="fastqc_1"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=12
#SBATCH --time=12:00:00
#SBATCH --mem=32G
#SBATCH --ntasks=1
#SBATCH --partition=pibu_el8

module load MultiQC/1.11-foss-2021a

WORKDIR="/data/users/mjacquey/RNA_seq_project"
FASTQCDIR="$WORKDIR/trim_result"

multiqc $FASTQCDIR/*trim_fastqc.zip --outdir /data/users/mjacquey/RNA_seq_project/multiQC_result/multiQC_report_after_trimming.html

